[package]
name = "wasm-mod-runtime"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
structopt = "0.3.26"
# Don't want WASI, security hole.
wasmer = "2.3.0"
wasmer-compiler-singlepass = "2.3.0"
#llvm